### ISSUE TITLE
Bug: int() argument must be a string, a bytes-like object or a number, not 'Tache'

### ISSUE THREAD

**Issue by hugopanel** [hugopanel/projet-graphes#21]
```
Traceback (most recent call last):
  File "/Users/hugop/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/231.8109.197/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/Users/hugop/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/231.8109.197/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Users/hugop/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/231.8109.197/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/hugop/Library/CloudStorage/OneDrive-Efrei/S6/Théorie des graphes/Projet/projet-graphes/main.py", line 433, in <module>
    graphe = trier_graphe(graphe)
  File "/Users/hugop/Library/CloudStorage/OneDrive-Efrei/S6/Théorie des graphes/Projet/projet-graphes/main.py", line 94, in trier_graphe
    if int(tache.nom) == i:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tache'
```

L'erreur se produit dans la fonction trier_graphe() parce qu'un sommet porte une tâche comme nom.

**Comment by hugopanel** [comment]
Sûrement liée à un mauvais refactoring dans #20 !
On a tache = tache ligne 29 !
